version: "3.5"
services:
  mysql:
    image: mysql:5.7
    volumes:
    - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=benchmark
      - MYSQL_PASSWORD=benchmark
    ports:
      - 3306:3306
  webserver:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8001:80
    depends_on:
      - symfony5
  symfony5:
    image: phpvigo/api-benchmark-symfony5:latest
  reactphp:
    image: phpvigo/api-benchmark-reactphp:latest
    ports:
      - 8000:8000
    environment:
      - ORM_ACTIVE=1
  reactphp-no-orm:
    image: phpvigo/api-benchmark-reactphp:latest
    ports:
      - 8004:8000
    environment:
      - ORM_ACTIVE=0
  node:
    image: phpvigo/api-benchmark-node:latest
    ports:
      - 8002:80
  go:
    image: phpvigo/api-benchmark-golang:latest
    ports:
      - 8003:8080
  vegeta:
    build:
      context: .
      dockerfile: vegeta/Dockerfile
    ports:
      - 8080:80
  ab:
    build:
      context: .
      dockerfile: ab/Dockerfile
    ports:
      - 8081:80
